#=============================================================================
#         FILE:  sc.conf.pod
#  DESCRIPTION:  Source for sc.conf(5) manpage
#       AUTHOR:  Stanislav Kruchinin, <stanislav.krucinin@gmail.com>
#=============================================================================


=head1 NAME

B<sc.conf> - configuration file for sc(8).

=head1 DESCRIPTION

The F<sc.conf> is parsed using C<AppConfig> module and has a simple C<variable
= value> form.
Expansion for internal and environment variables is enabled (see AppConfig(3)
for details).
The file may contain extra tabs and newlines for formatting.
Comments begin with the B<#> character and end at the end of line, like in
shell or Perl scripts.

=head1 OPTIONS

=over

=item B<tc>

Location of tc(8) executable.

=item B<out_if>, B<in_if>

Names of the interfaces that will be used for shaping of output and input
traffic, respectively.
Possible values: interface name or "disable" keyword, which disables rule
generation.

=item B<limit_method>

Rate limiting method.

Default value: B<shaping>.

Possible values: B<shaping>, B<policing>, B<hybrid>.

The B<hybrid> method uses shaping for download and policing for upload, and
all the rules are created on the B<in_if> interface.
This is suitable, when NAT is performed on the outbound interface.

=item B<debug>

Debug modes.

Default value: B<0>.

Possible values:

=over

=item B<0>

no debug (default value),

=item B<1>

print command lines with nonzero return values,

=item B<2>

print all command lines without execution.

=back

=item B<verbose>

When enabled, turns on verbose messages and disables piping of tc(8) rules.

Default value: B<0>.

Possible values:

=over

=item B<0>

no verbose messages (default)

=item B<1>

enable verbose messages (i.e. for results of `sync' command)

=item B<2>

disable batch loading of rules for tc(8)

=item B<3>

do B<1> + B<2>

=back

=item B<quiet>

Suppress output. Does not affect messages caused by C<verbose> flag.

Default value: B<0>.

Possible values: boolean.

=item B<colored>

Colorize output using ANSI escape sequences.
Autodetection of non-tty handles is supported.

Default value: B<1>.

Possible values: boolean.

=item B<joint>

Perform B<add>, B<change> and B<delete> operations on rules and database with
a single command.

=item B<network>

This variable contains the list of networks for classid calculation.
These networks must cover all IPs which you are going to use in shaping rules.

Default value: B<10.0.0.0/16>.

Possible values: a list of networks with mask from 16 to 31 method.

Total number of hosts in the specified networks should not exceed the maximum
number of child classes: 65533 (from 2 to fffd, because fffe is reserved for
default class, and ffff is for ingress policer).

=item B<filter_network>

Network list for hashing filters generation.
To improve the classification performance you may specify here a summarized
network just like in case of supernetting (route aggregation).
For example, if you have the following networks

	network = 10.0.0.0/20 10.0.253.0/24 10.0.254.0/24

you should specify a single 10.0.0.0/16 network to classify traffic
by a single hashing filter

	filter_network = 10.0.0.0/16

Default value: same as B<network> parameter.

Possible values: a list of networks with mask from 16 to 31, that includes the
networks specified in B<network> parameter.

=item B<bypass_int>

List of internal networks and IPs, whose traffic is transmitted without
shaping.

Default value: B<empty>.

Possible values: space-separated list of networks with masks from 16 to 32.

=item B<bypass_ext>

List of external networks and IPs, whose traffic is transmitted without
shaping.

Default value: B<empty>.

Possible values: space-separated list of networks with masks from 16 to 32.

=item B<policer_burst_ratio>

Ratio between the size of policer buffer size and bandwidth rate.

Default value: B<0.1>.

=item B<quantum>

Amount of bytes a stream is allowed to dequeue before the next queue gets a
turn.

Default value: B<1500>.

Possible values: integer numbers >= MTU of the interface.

=item B<rate_unit>

Default rate unit.

Default value: B<kibit>.

Possible values: see sc(8) or tc(8) manpage.

=item B<rate_ratio>

Ratio between bandwidth rates in rules and in the database.
  rule_rate = db_rate * rate_ratio

This coefficient is used only for B<load> and B<sync> commands.

Default value: B<1.0>.

Possible values: any rational number.

=item B<root_qdisc>

Root queueing discipline.

Default value: B<htb>.

Possible values: B<htb> or B<hfsc>.

=item B<leaf_qdisc>

Leaf queueing discipline with parameters.
This string will be used as a tail of corresponding C<tc qdisc ...> command
line.

Default value: B<pfifo limit 100>.

Possible values: all classless qdiscs supported by tc(8).

=item B<db_host>

Database host.

Default value: B<127.0.0.1>.

Possible values: IP-address or domain name.

=item B<db_driver>

Database driver.

Default value: B<SQLite>.

Possible values: all database drivers supported by Perl DBI module.
See output of C<sc help> command for the list of available drivers.

=item B<db_user>

Username to use when connecting to database.

Default value: B<user>.

Possible values: depends on database server.

=item B<db_pass>

The password to use when connecting to database. Remember that specifying a
password on the command line is insecure.

Default value: B<password>.

Possible values: arbitrary string.

=item B<db_name>

Database name to use.

Default value: B<sc.db>.

Possible values: arbibrary string (should be a valid filename in case of
SQLite driver).

=item B<Database queries>

=over 16

=item B<query_create>

Create table with C<ip> and C<rate> columns.

=item B<query_load>

Select all data from table.

=item B<query_list>

Select data for one IP.

=item B<query_add>

add a new entry.

=item B<query_del>

delete an existing entry.

=item B<query_change>

modify an existing entry.

=back

=item B<syslog>

Output errors and warnings to syslog.

Default value: B<1>.

Possible values: boolean.

=item B<syslog_options>

Default value: B<<empty string>>.

Possible values (comma-separated):

=over 12

=item B<ndelay>

open the connection immediately

=item B<nofatal>

just emit warnings instead of dying if the connection to syslog can't be
established

=item B<perror>

write the message to standard error output as well to the syslog

=item B<pid>

include PID with each message

=back

=item B<syslog_facility>

Default value: B<user>.

Possible values: see Sys::Syslog(3), section C<Facilities>.

=back

=head1 SEE ALSO

sc(8), tc(8), tc-htb(8), tc-hfsc(8), tc-u32(8), tc-pfifo(8),
AppConfig(3), Sys::Syslog(3).
http://lartc.org/howto/lartc.adv-filter.hashing.html,
http://ace-host.stuart.id.au/russell/files/tc/doc/cls_u32.txt.

=head1 AUTHOR

Stanislav Kruchinin <stanislav.kruchinin@gmail.com>

=cut

# vim:set syntax=pod:

